# Generated by Django 5.1.1 on 2025-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('description', models.TextField()),
                ('supplier', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('previous_restock_date', models.DateField(blank=True, null=True)),
                ('next_restock_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
